import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* <nav className='nav-bar'>
        <button className="btn nav-menu">Home</button>
        <button onClick={handleLogout} className="btn btn-danger">
            Logout
        </button>
        <div className="profile-container" style={{ display: 'flex', alignItems: 'center', marginLeft: '900px' }}>
            <img
            src={`${API_URL}/public/uploads/${userimage}`}
            alt="User Profile"
            style={{
                width: '40px',
                height: '40px',
                borderRadius: '50%',
                marginRight: '2px',
            }}
            />
            <p className="mt-2 ml-3">{userFirst}</p>
        </div>
        </nav> */}
        {children}
      </body>
    </html>
  );
}
